#ansible-playbook clone_github_repos.yml -e @terraform-repos.yml
- name: Clone GitHub repositories
  hosts: localhost
  become: no
  tasks:
    - name: Create destination folder
      file:
        path: "{{ dest_folder }}"
        state: directory

    - name: Clone repositories
      git:
        repo: "{{ item.url }}"
        dest: "{{ dest_folder }}/{{ item.name }}"
      loop: "{{ repo_list }}"

    - name: Create new branch
      git:
        repo: "{{ dest_folder }}/{{ item.name }}"
        ref: "refs/heads/{{ branch }}"
        state: present
      loop: "{{ repo_list }}"

    - name: Checkout new branch
      git:
        repo: "{{ item.url }}"
        dest: "{{ dest_folder }}/{{ item.name }}"
        version: "{{ branch }}"
      loop: "{{ repo_list }}"
